const comidas = [
  {
    tipo: 'desayuno',
    contorno: 'huevos',
    proteina: 'tocineta',
    bebida: 'jugo de naranja',
    extra: 'queso',
    postre: 'yogur',
  },
  {
    tipo: 'desayuno',
    contorno: 'empanada',
    proteina: 'carne',
    bebida: 'malta',
    extra: 'salsa picante',
    postre: 'dulce',
  },
  {
    tipo: 'almuerzo',
    contorno: 'arroz',
    proteina: 'pollo',
    bebida: 'soda',
    extra: 'aguacate',
    postre: 'marquesa',
  },
  {
    tipo: 'almuerzo',
    contorno: 'pasta',
    proteina: 'camarones',
    bebida: 'vino tinto',
    extra: 'casabe al horno',
    postre: 'helado',
  },
  {
    tipo: 'cena',
    contorno: 'arepa',
    proteina: 'jamon',
    bebida: 'malta',
    extra: 'mantequilla',
    postre: 'ensalada de frutas',
  },
  {
    tipo: 'cena',
    contorno: 'tacos',
    proteina: 'carne y pollo',
    bebida: 'soda',
    extra: 'salsa verde',
    postre: 'torta de chocolate',
  },
];
